# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enx00e04c68088e:
      dhcp4: no
      addresses:
        - 192.168.4.2/24
      routes:
        - to: default
          via: 192.168.4.1
      nameservers:
        addresses: [192.168.4.1, 8.8.8.8]
